# Generated by Django 3.1.2 on 2021-02-25 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='p_image',
            field=models.FileField(default='default.jpg', upload_to='product_pics'),
        ),
    ]
