# Generated by Django 3.1.2 on 2021-03-08 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_customizeable'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomizeItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.orderitem')),
            ],
        ),
    ]
