# Generated by Django 3.1.2 on 2020-12-03 17:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0002_auto_20201130_2137'),
    ]

    #operations = [
    #    migrations.AlterField(
    #        model_name='payment',
    #        name='id',
    #        field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
    #    ),
    #]
