# Generated by Django 3.1.2 on 2020-12-03 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0003_auto_20201203_1743'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
