# Generated by Django 3.1.2 on 2020-12-29 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0008_auto_20201209_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name='payment',
            name='receipt_img',
            field=models.ImageField(default='default.jpg', upload_to='receipt_pics'),
        ),
    ]
