# Generated by Django 3.1.2 on 2021-02-22 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0011_auto_20201230_1526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='status',
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('COMPLETE', 'Complete'), ('INCOMPLETE', 'Incomplete')], default='INCOMPLETE', max_length=10),
        ),
    ]
