# Generated by Django 3.1.2 on 2021-02-23 04:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0013_auto_20210222_1625'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('invoice_id', models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('COMPLETE', 'Complete'), ('INCOMPLETE', 'Incomplete'), ('TRANSIT', 'Transit')], default='INCOMPLETE', max_length=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='type',
            field=models.CharField(choices=[('Contribution', 'Contribution'), ('Personal Expense', 'Personal Expense'), ('Company Expense', 'Company Expense'), ('Invoice', 'Invoice')], default='Contribution', max_length=22),
        ),
    ]
